// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBadmGqpQGoHyd1AEjwK8ApLd3yHOg5i9o',
    appId: '1:236450143936:web:161e8ddce1e48a42ac1725',
    messagingSenderId: '236450143936',
    projectId: 'flu-firebase-application',
    authDomain: 'flu-firebase-application.firebaseapp.com',
    storageBucket: 'flu-firebase-application.firebasestorage.app',
    measurementId: 'G-8KQFS1JHDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_v-fF_fRmMF0YQYmDdANZv8yASPHoVY',
    appId: '1:236450143936:android:a327010f62a9287aac1725',
    messagingSenderId: '236450143936',
    projectId: 'flu-firebase-application',
    storageBucket: 'flu-firebase-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_Rorxvt3w0KvCq1H72Xz4g8IPpzBj-w',
    appId: '1:236450143936:ios:c24485369bd5257dac1725',
    messagingSenderId: '236450143936',
    projectId: 'flu-firebase-application',
    storageBucket: 'flu-firebase-application.firebasestorage.app',
    iosBundleId: 'com.example.fluFirebaseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_Rorxvt3w0KvCq1H72Xz4g8IPpzBj-w',
    appId: '1:236450143936:ios:c24485369bd5257dac1725',
    messagingSenderId: '236450143936',
    projectId: 'flu-firebase-application',
    storageBucket: 'flu-firebase-application.firebasestorage.app',
    iosBundleId: 'com.example.fluFirebaseApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBadmGqpQGoHyd1AEjwK8ApLd3yHOg5i9o',
    appId: '1:236450143936:web:e9826b85e1ff657cac1725',
    messagingSenderId: '236450143936',
    projectId: 'flu-firebase-application',
    authDomain: 'flu-firebase-application.firebaseapp.com',
    storageBucket: 'flu-firebase-application.firebasestorage.app',
    measurementId: 'G-WH9SVHMBW6',
  );
}
